### ISSUE TITLE
Optimization : Dark Mode

### ISSUE THREAD

**Issue by GuangChen2333** [leaf2006/EMUL#3]
### Header
Changed from the original `#111111` to `#202124`

### Background Color
Changed from the original 
```css
body{
    background-color: #181818;
}
```
to
```css
body {
    background-color: #35363A;
    font-family: Roboto, 'Segoe UI', Arial, 'Microsoft Yahei', sans-serif;
    color: #E8EAED;
    font-size: calc(100% - 1px);
    line-height: calc(100% + 6px);
}
```

### New Styles
- Borderless button unique to dark mode
- Check box unique to dark mode
- Group box unique to dark mode

> 今天又是个把Issues当做更新日志的一天呢~
